/*
Test generated by RoostGPT for test golang-sample-programs using AI Type Open AI and AI Model gpt-4

12. Test Scenario: Test with a string that has multiple spaces between words but is a palindrome. The function should return false as it doesn't ignore multiple spaces. Example: "A   man   a   plan   a   canal   Panama"

*/
package palindrome

import (
	"strings"
	"testing"
)

func TestIsPalindromeRecursiveHelper_6ebf394e0a(t *testing.T) {

	tests := []struct {
		name     string
		input    string
		expected bool
	}{
		{
			name:     "Test with empty string",
			input:    "",
			expected: true,
		},
		{
			name:     "Test with a single character string",
			input:    "a",
			expected: true,
		},
		{
			name:     "Test with a palindrome string",
			input:    "madam",
			expected: true,
		},
		{
			name:     "Test with a non-palindrome string",
			input:    "hello",
			expected: false,
		},
		{
			name:     "Test with a string that has spaces but is a palindrome",
			input:    "A man a plan a canal Panama",
			expected: false,
		},
		{
			name:     "Test with a string that has mixed case but is a palindrome",
			input:    "Madam",
			expected: false,
		},
		{
			name:     "Test with a string that includes punctuation and is a palindrome",
			input:    "Able, was I saw Elba.",
			expected: false,
		},
		{
			name:     "Test with a string that includes numbers",
			input:    "12321",
			expected: true,
		},
		{
			name:     "Test with a string that includes special characters",
			input:    "@@@",
			expected: true,
		},
		{
			name:     "Test with a very long string",
			input:    strings.Repeat("a", 1<<20) + "b" + strings.Repeat("a", 1<<20),
			expected: false,
		},
		{
			name:     "Test with non-ASCII characters",
			input:    "åbba",
			expected: true,
		},
		{
			name:     "Test with a string that has multiple spaces between words but is a palindrome",
			input:    "A   man   a   plan   a   canal   Panama",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			runes := []rune(tt.input)
			if got := isPalindromeRecursiveHelper(runes, 0, int64(len(runes))); got != tt.expected {
				t.Errorf("isPalindromeRecursiveHelper() = %v, want %v", got, tt.expected)
			}
		})
	}
}
